// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication2.Data.DbContexts;

#nullable disable

namespace WebApplication2.Data.Migrations.Master
{
    [DbContext(typeof(MasterDbContext))]
    partial class MasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotificacion"));

                    b.Property<string>("AccionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EmailEnviado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEmailEnviado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdTenant")
                        .HasColumnType("integer");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenantCodigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenantNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("IdTenant");

                    b.HasIndex("Leida");

                    b.HasIndex("Tipo");

                    b.ToTable("Notificacion");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.PlanLicencia", b =>
                {
                    b.Property<int>("IdPlanLicencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlanLicencia"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Caracteristicas")
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IncluyeAPI")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncluyeFacturacion")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncluyeReportes")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncluyeSoporte")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCampus")
                        .HasColumnType("integer");

                    b.Property<int>("MaxEstudiantes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsuarios")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrecioAnual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPlanLicencia");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("PlanLicencia");

                    b.HasData(
                        new
                        {
                            IdPlanLicencia = 1,
                            Activo = true,
                            Codigo = "BASIC",
                            Descripcion = "Plan básico para escuelas pequeñas",
                            IncluyeAPI = false,
                            IncluyeFacturacion = false,
                            IncluyeReportes = false,
                            IncluyeSoporte = false,
                            MaxCampus = 1,
                            MaxEstudiantes = 200,
                            MaxUsuarios = 5,
                            Nombre = "Básico",
                            Orden = 1,
                            PrecioAnual = 25000m,
                            PrecioMensual = 2500m
                        },
                        new
                        {
                            IdPlanLicencia = 2,
                            Activo = true,
                            Codigo = "PRO",
                            Descripcion = "Plan profesional para escuelas medianas",
                            IncluyeAPI = false,
                            IncluyeFacturacion = false,
                            IncluyeReportes = true,
                            IncluyeSoporte = true,
                            MaxCampus = 3,
                            MaxEstudiantes = 1000,
                            MaxUsuarios = 20,
                            Nombre = "Profesional",
                            Orden = 2,
                            PrecioAnual = 50000m,
                            PrecioMensual = 5000m
                        },
                        new
                        {
                            IdPlanLicencia = 3,
                            Activo = true,
                            Codigo = "ENTERPRISE",
                            Descripcion = "Plan enterprise para universidades y grandes instituciones",
                            IncluyeAPI = true,
                            IncluyeFacturacion = true,
                            IncluyeReportes = true,
                            IncluyeSoporte = true,
                            MaxCampus = 10,
                            MaxEstudiantes = 50000,
                            MaxUsuarios = 100,
                            Nombre = "Enterprise",
                            Orden = 3,
                            PrecioAnual = 150000m,
                            PrecioMensual = 15000m
                        });
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.SuperAdmin", b =>
                {
                    b.Property<int>("IdSuperAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSuperAdmin"));

                    b.Property<bool>("AccesoTotal")
                        .HasColumnType("boolean");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastLoginIP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSuperAdmin");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("SuperAdmin");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.SuperAdminTenant", b =>
                {
                    b.Property<int>("IdSuperAdminTenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSuperAdminTenant"));

                    b.Property<DateTime>("AsignadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdSuperAdmin")
                        .HasColumnType("integer");

                    b.Property<int>("IdTenant")
                        .HasColumnType("integer");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdSuperAdminTenant");

                    b.HasIndex("IdTenant");

                    b.HasIndex("IdSuperAdmin", "IdTenant")
                        .IsUnique();

                    b.ToTable("SuperAdminTenant");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.Tenant", b =>
                {
                    b.Property<int>("IdTenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTenant"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ColorPrimario")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ColorSecundario")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DireccionFiscal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DominioPersonalizado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailContacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPlanLicencia")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaximoEstudiantes")
                        .HasColumnType("integer");

                    b.Property<int>("MaximoUsuarios")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NombreCorto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RFC")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdTenant");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("DatabaseName")
                        .IsUnique();

                    b.HasIndex("IdPlanLicencia");

                    b.HasIndex("Status");

                    b.HasIndex("Subdominio")
                        .IsUnique();

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.TenantAuditLog", b =>
                {
                    b.Property<long>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdLog"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Detalles")
                        .HasColumnType("text");

                    b.Property<int?>("IdSuperAdmin")
                        .HasColumnType("integer");

                    b.Property<int?>("IdTenant")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IdLog");

                    b.HasIndex("Accion");

                    b.HasIndex("IdSuperAdmin");

                    b.HasIndex("IdTenant");

                    b.HasIndex("Timestamp");

                    b.ToTable("TenantAuditLog");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.Notificacion", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.MultiTenant.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.SuperAdminTenant", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.MultiTenant.SuperAdmin", "SuperAdmin")
                        .WithMany("TenantAccess")
                        .HasForeignKey("IdSuperAdmin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication2.Core.Models.MultiTenant.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuperAdmin");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.Tenant", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.MultiTenant.PlanLicencia", "PlanLicencia")
                        .WithMany("Tenants")
                        .HasForeignKey("IdPlanLicencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanLicencia");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.TenantAuditLog", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.MultiTenant.SuperAdmin", "SuperAdmin")
                        .WithMany()
                        .HasForeignKey("IdSuperAdmin");

                    b.HasOne("WebApplication2.Core.Models.MultiTenant.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("IdTenant");

                    b.Navigation("SuperAdmin");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.PlanLicencia", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MultiTenant.SuperAdmin", b =>
                {
                    b.Navigation("TenantAccess");
                });
#pragma warning restore 612, 618
        }
    }
}
